import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { corsHeaders } from '../_shared/cors.ts'

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    )

    // Verify user
    const userClient = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } },
    )
    const { data: { user }, error: authError } = await userClient.auth.getUser()
    if (authError || !user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const { review_id } = await req.json()

    // Fetch review + comments
    const { data: review } = await supabase
      .from('reviews')
      .select('*')
      .eq('id', review_id)
      .eq('user_id', user.id)
      .single()

    if (!review || review.status !== 'completed') {
      return new Response(JSON.stringify({ error: 'Review not found or not completed' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const { data: comments } = await supabase
      .from('review_comments')
      .select('*')
      .eq('review_id', review_id)

    // Get GitHub token
    const { data: settings } = await supabase
      .from('user_settings')
      .select('github_token_encrypted')
      .eq('user_id', user.id)
      .single()

    const githubToken = settings?.github_token_encrypted
    if (!githubToken) {
      return new Response(JSON.stringify({ error: 'GitHub token not found' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const [owner, repo] = review.repo_full_name.split('/')

    // Build review body
    const severityEmoji: Record<string, string> = {
      P1: '🔴',
      P2: '🟠',
      P3: '🔵',
      P4: '🟢',
      P5: '⭐',
    }

    let body = `## AI Code Review\n\n${review.summary || ''}\n\n`
    body += `**Provider**: ${review.provider === 'claude' ? 'Claude' : 'OpenAI'}\n\n`

    if (comments && comments.length > 0) {
      body += `### Comments (${comments.length})\n\n`
      for (const comment of comments) {
        const emoji = severityEmoji[comment.severity] || '⚪'
        const lineRef = comment.start_line
          ? `\`${comment.file_path}:${comment.start_line}${comment.end_line && comment.end_line !== comment.start_line ? `-${comment.end_line}` : ''}\``
          : `\`${comment.file_path}\``
        body += `${emoji} **${comment.severity}** - ${lineRef}\n${comment.body}\n\n`
      }
    }

    body += `\n---\n*Generated by [Review Seal](https://github.com/review-seal)*`

    // TODO: Post as a proper PR review with line comments using GitHub's
    // POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews API
    // For now, post as a single issue comment for simplicity
    const ghResponse = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues/${review.pr_number}/comments`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
        body: JSON.stringify({ body }),
      },
    )

    if (!ghResponse.ok) {
      const errorText = await ghResponse.text()
      return new Response(
        JSON.stringify({ error: `GitHub API error: ${ghResponse.status} - ${errorText}` }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
      )
    }

    const ghData = await ghResponse.json()

    // Update review status
    await supabase
      .from('reviews')
      .update({
        status: 'posted',
        posted_at: new Date().toISOString(),
        github_review_id: ghData.id,
      })
      .eq('id', review_id)

    // TODO: Slack notification
    // if (settings.slack_webhook_url) {
    //   await fetch(settings.slack_webhook_url, {
    //     method: 'POST',
    //     headers: { 'Content-Type': 'application/json' },
    //     body: JSON.stringify({
    //       text: `Review Seal: Review posted for ${review.repo_full_name}#${review.pr_number}`,
    //     }),
    //   })
    // }

    return new Response(
      JSON.stringify({ success: true, github_comment_id: ghData.id }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    )
  } catch (error) {
    console.error('post-review error:', error)
    return new Response(
      JSON.stringify({ error: String(error) }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    )
  }
})
