/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReposIndexRouteImport } from './routes/repos/index'
import { Route as PrsIndexRouteImport } from './routes/prs/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PrsOwnerRepoPrNumberRouteImport } from './routes/prs/$owner.$repo.$prNumber'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsIndexRoute = PrsIndexRouteImport.update({
  id: '/prs/',
  path: '/prs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsOwnerRepoPrNumberRoute = PrsOwnerRepoPrNumberRouteImport.update({
  id: '/prs/$owner/$repo/$prNumber',
  path: '/prs/$owner/$repo/$prNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/prs/': typeof PrsIndexRoute
  '/repos/': typeof ReposIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/prs/$owner/$repo/$prNumber': typeof PrsOwnerRepoPrNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/prs': typeof PrsIndexRoute
  '/repos': typeof ReposIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/prs/$owner/$repo/$prNumber': typeof PrsOwnerRepoPrNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/prs/': typeof PrsIndexRoute
  '/repos/': typeof ReposIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/prs/$owner/$repo/$prNumber': typeof PrsOwnerRepoPrNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/prs/'
    | '/repos/'
    | '/settings/'
    | '/prs/$owner/$repo/$prNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/prs'
    | '/repos'
    | '/settings'
    | '/prs/$owner/$repo/$prNumber'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/callback'
    | '/prs/'
    | '/repos/'
    | '/settings/'
    | '/prs/$owner/$repo/$prNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PrsIndexRoute: typeof PrsIndexRoute
  ReposIndexRoute: typeof ReposIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  PrsOwnerRepoPrNumberRoute: typeof PrsOwnerRepoPrNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs/': {
      id: '/prs/'
      path: '/prs'
      fullPath: '/prs/'
      preLoaderRoute: typeof PrsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs/$owner/$repo/$prNumber': {
      id: '/prs/$owner/$repo/$prNumber'
      path: '/prs/$owner/$repo/$prNumber'
      fullPath: '/prs/$owner/$repo/$prNumber'
      preLoaderRoute: typeof PrsOwnerRepoPrNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PrsIndexRoute: PrsIndexRoute,
  ReposIndexRoute: ReposIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  PrsOwnerRepoPrNumberRoute: PrsOwnerRepoPrNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
